### PR TITLE
Apply custom background to selected date

### PR DESCRIPTION
**Pull request by Zey-Uzh**
Change selectedDateBackground (accepts only color) to selectedDateBackgroundDrawable (accepts drawable).
You can set background from builder, from HorizontalCalendar object, or from xml.
#40

### CODE REVIEW

**Comment by Mulham-Raee** [comment]
Hello @Zey-Uzh 

Thanks for your contribution, but I can't merge this pull request for multiple reasons:
1- selected Background drawable is not being applied in the adapter.
2- selection view is now a lot shorter for some reason.
3- you made some adjustments to the item_calendar.xml which I don't see any need for.

**Comment by Zey-Uzh** [comment]
Greetings, thank you for your comments. I'll try to fix these problems.

**Comment by Zey-Uzh** [comment]
I returned the original layer and made the full width for the selection view. And now you can hide the bottom selection line by setting the color to Color.TRANSPARENT

**Comment by Mulham-Raee** [comment]
@Zey-Uzh  I have made a commit as well fixing some issues and merged your pull request,
Thanks for your contribution.

**Pull request merged**
